###
POST http://localhost:3000/customer/queue
Content-Type: application/json

{
  "queueId": "nails"
}

###
POST http://localhost:3000/admin/next
Content-Type: application/json

{
  "queueId": "nails"
}

###
GET http://localhost:3000/admin/meta?queueId=nails
