###
POST http://localhost:3000/customer/queue
Content-Type: application/json

{
  "queueId": "ligma"
}

###
POST http://localhost:3000/admin/serve
Content-Type: application/json

{
  "queueId": "ligma",
  "joinId": "ligma-2"
}
